### ISSUE TITLE
Refactor config file versioning

### ISSUE THREAD

**Issue by maehler** [gmc-norr/scout-annotation#3]
The current config uses a single version for the vcfanno config, regardless of the sample type (track). It should be possible to use different versions for different tracks. Combining the current solution for vcfanno and genmod config should make this prettier, so something like

```yaml
vcfanno:
  config_uri: "https://raw.githubusercontent.com/gmc-norr/config-files/main/{track}/vcfanno/grch37_vcfanno_config_{version}.toml"
  config_version:
    rare_disease: "0.1"
    cancer: "0.1"

genmod:
  rank_model_uri: "https://raw.githubusercontent.com/gmc-norr/config-files/main/{track}/rank_model/rank_model_{version}.ini"
  rank_model_version:
    rare_disease: "0.1"
    cancer: "0.1"
```
